module.exports={
    root:process.cwd(),//当前Node.js进程执行时的工作目录
    hostname:'0.0.0.0',
    port:8000,
    compress:/\.(html|js|css|md)/,
    cache:{
        maxAge:600,
        expires:true,
        cacheControl:true,
        lastModified:true,
        etag:true
    }
};